### PR TITLE
Cleanup instructors

### PR DESCRIPTION
**Pull request by githubstudent**
- Removed instructors from read me
- Added links to instructor profiles
- Added home-base location
# What it looks like now:

screen shot 2015-03-24 at 10 54 04 am

### CODE REVIEW

**Comment by githubstudent** [comment]
@githubteacher @jordanmccullough can one of you review this pull request?

**Comment by jordanmccullough** [comment]
@githubstudent, Happy to take a look! Give me a couple minutes to look over the edits.

**Comment by jordanmccullough** [comment]
How about we add full names and then :ship: this?

**Comment by githubteacher** [comment]
:+1: This looks good to me. :ship: it.

**Comment by jordanmccullough** [comment]
@githubteacher, Would you agree the edits with full names would be a good idea?

**Comment by githubteacher** [comment]
Yes, @jordanmccullough has the right idea, let’s use full names.

**Comment by jordanmccullough** [comment]
yes

**Comment by jordanmccullough** [comment]
Showing how file review and code commenting might work on GitHub and PRs.
markdown

**Comment by githubstudent** [comment]
excited

**Pull request merged**
